# Generated by Django 5.0.6 on 2024-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationmodel',
            name='code',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
