# Generated by Django 5.0.6 on 2024-07-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_storymodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storymodel',
            options={'ordering': ('-expire_time',), 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RenameField(
            model_name='storymodel',
            old_name='expiry_time',
            new_name='expire_time',
        ),
    ]
